CREATE TABLE dim_project (
  project_id   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  project_code VARCHAR2(4),
  project_name VARCHAR2(30)
);
/


DROP TABLE activity_facts; 
DROP TABLE event_facts; 
DROP TABLE dim_events; 

CREATE TABLE dim_events (
event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
summary VARCHAR(100),
description VARCHAR(200),
start_time DATE,
end_time DATE
);

CREATE TABLE activity_facts(
activity_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
employee_id NUMBER REFERENCES dim_employee(employee_id),
project_id NUMBER REFERENCES dim_project(project_id),
date_id NUMBER REFERENCES dim_date,
hours_worked NUMBER(4,2)
);
/
CREATE TABLE absence_facts(
event_fact_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
employee_id NUMBER REFERENCES dim_employee(employee_id),
event_id NUMBER REFERENCES dim_events(event_id),
date_id NUMBER REFERENCES dim_date,
time_spent NUMBER(5,2)
);



CREATE TABLE DIM_MEETINGS(
event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title VARCHAR(100),
start_time DATE,
end_time DATE
)


CREATE TABLE attendence_facts(
attendence_fact_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
employee_id NUMBER REFERENCES dim_employee(employee_id),
meeting_id NUMBER REFERENCES dim_meetings(meeting_id),
date_id NUMBER REFERENCES dim_date,
time_spent NUMBER(5,2),
role VARCHAR(30)
);